Modules/Languages/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin/')->group(function() {
//    Route::get('/', 'LanguagesController@index');
    Route::resource('languages','LanguagesController');
});

Modules/Languages/Models/Local.php
<?php

namespace Modules\Languages\Models;

use Illuminate\Database\Eloquent\Model;

class Local extends Model
{
    protected $fillable = ['local_name','code','direction'];
}

Modules/Languages/Models/Translation.php
<?php

namespace Modules\Languages\Models;

use Illuminate\Database\Eloquent\Model;

class Translation extends Model
{
    protected $table='translations';


}

Modules/Languages/Http/Controllers/LanguagesController.php
<?php

namespace Modules\Languages\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\App;
use Modules\Languages\Http\Requests\LanguagesRequest;
use Modules\Languages\Models\Local;

class LanguagesController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $languages = Local::get();
        return view('languages::index',compact('languages'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('languages::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request|LanguagesRequest $request
     * @return Response
     */
    public function store(LanguagesRequest $request)
    {
        $inputs = $request->all();
        if (Local::create($inputs)) {
            flash()->success('Data was saved successfully');
            return redirect()->route('languages.index');
        } else {
            flash()->error('Failed to save data, please try again later');
        }
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show()
    {
        return view('languages::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($local_id)
    {
        $language = Local::findOrFail($local_id);
        return view('languages::edit',compact('language'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request|LanguagesRequest $request
     * @param $local_id
     * @return Response
     */
    public function update(LanguagesRequest $request,$local_id)
    {
        $language = Local::findOrFail($local_id);
        $inputs = $request->all();
        if ($language->update($inputs)) {
            flash()->success('Data was saved successfully');
            return redirect()->route('languages.index');
        } else {
            flash()->error('Failed to save data, please try again later');
        }
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy($local_id)
    {
        $language = Local::findOrFail($local_id);

        if ($language->delete()) {
            flash()->success('Data was deleted successfully');
        } else {
            flash()->error('failed to delete data, please try again later');
        }
        return redirect()->back();
    }
}

Modules/Languages/Resources/views/create.blade.php
@extends('admin.layouts.master')

@section('content')
@section('menu', 'Settings')
@section('name','Language')
<div class="row clearfix">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h2>Create Language</h2>
            </div>
            <div class="body">
                {!! BootForm::open('create', ['url'=>route('languages.store'),'novalidate','id'=>'basic-form']) !!}
                {!! BootForm::input('text', 'local_name', null, 'Name', $errors,['required','data-parsley-length'=>'[3,20]']) !!}
                {!! BootForm::input('text', 'code', null, 'Code', $errors,['required','data-parsley-maxlength'=>'2']) !!}
                {!! BootForm::select('direction', 'Direction', ['ltr'=>'ltr','rtl'=>'rtl'], null, $errors,['required']) !!}
                <br>
                {!! BootForm::submit() !!}
                {!! BootForm::close() !!}

            </div>
        </div>
    </div>
</div>
@stop


@section('scripts')
    <script src="{{ asset('assets/vendor/parsleyjs/js/parsley.min.js') }}"></script>
    <script>
        $(function() {
            // initialize after multiselect
            $('#basic-form').parsley();
        });
    </script>
@endsection

Modules/Languages/Resources/views/edit.blade.php
@extends('admin.layouts.master')

@section('content')
@section('menu', 'Settings')
@section('name','Language')
<div class="row clearfix">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h2>Create Language</h2>
            </div>
            <div class="body">
                {!! BootForm::model($language, 'edit', ['method'=>'put', 'route'=>['languages.update',$language->id]]) !!}
                {!! BootForm::input('text', 'local_name', null, 'Name', $errors,['required','data-parsley-length'=>'[3,20]']) !!}
                {!! BootForm::input('text', 'code', null, 'Code', $errors,['required','data-parsley-maxlength'=>'2']) !!}
                {!! BootForm::select('direction', 'Direction', ['ltr'=>'ltr','rtl'=>'rtl'], null, $errors,['required']) !!}
                <br>
                {!! BootForm::submit() !!}
                {!! BootForm::close() !!}

            </div>
        </div>
    </div>
</div>
@stop


@section('scripts')
    <script src="{{ asset('assets/vendor/parsleyjs/js/parsley.min.js') }}"></script>
    <script>
        $(function() {
            // initialize after multiselect
            $('#basic-form').parsley();
        });
    </script>
@endsection

Modules/Languages/Resources/views/index.blade.php
@extends('admin.layouts.master')

@section('content')
@section('menu', 'Settings')
@section('name','Language')
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card">
            <div class="header">
                <a class="btn btn-default" href="{{route('languages.create')}}"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Language</a>
            </div>
            <div class="body">
                <table id="mainTable" class="table table-hover">
                    <thead>

                    <tr>
                        <th>Name</th>
                        <th>Code</th>
                        <th>Directions</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($languages as $language)
                        <tr>
                            <td>{{$language->local_name}}</td>
                            <td>{{$language->code}}</td>
                            <td>{{$language->direction}}</td>
                            <td>
                                {!! BootForm::linkOfEdit('languages.edit', [$language->id], $language->local_name) !!}
                                {!! BootForm::linkOfDelete('languages.destroy', [$language->id], $language->local_name, 'link', true) !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop